export const GetExtraction = {
  FAILURE: "GET_EXTRACTION_FAILURE",
  REQUEST: "GET_EXTRACTION_REQUEST",
  SUCCESS: "GET_EXTRACTION_SUCCESS",
};

export const ClearExtractionState = {
  DEFAULT: "CLEAR_EXTRACTION_STATE_DEFAULT",
};
