export const GetExtraction = {
  FAILURE: "GET_EXTRACTION_FAILURE",
  SUCCESS: "GET_EXTRACTION_SUCCESS",
  REQUEST: "GET_EXTRACTION_REQUEST",
}

export const ClearExtractionState = {
  DEFAULT: "CLEAR_EXTRACTION_STATE_DEFAULT",
}
